### ISSUE TITLE
dex2jar (REMnux7)- Can we add this please? 

### ISSUE THREAD

**Issue by citizenstaar** [REMnux/salt-states#46] opened 2020-06-14 13:27 UTC
Not sure the preference on the format for requesting tools.  But can we please add dex2jar.  

Thank you for reviewing.

**Comment by lennyzeltser** [comment] 2020-06-16 01:24
Done. Thanks for the suggestion.

You'll get the dex2jar package if you run `remnux upgrade`. Could you give it a try, please, to confirm it installs correctly?

**Comment by citizenstaar** [comment] 2020-06-16 02:31
__sls__: remnux.packages.dex2jar
    changes: {}
    comment: "Problem encountered installing package(s). Additional info follows:\n\nerrors:\n
      \   - Running scope as unit: run-rfafaf596b13942898abe4928079cb126.scope\n      E:
      Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify
      a solution)."
    duration: 667.667
    name: dex2jar
    result: false
    start_time: '22:21:22.721752'

**Comment by citizenstaar** [comment] 2020-06-16 02:31
**v2020.25.1**

**Comment by citizenstaar** [comment] 2020-06-16 02:33
Do you want me to open a new issue?

**Comment by lennyzeltser** [comment] 2020-06-16 02:50
Hmm, I just tried it and it worked on my system. Could there be something odd with your APT database? Please try:

```
sudo apt update
sudo apt autoremove
```

Also, `apt --fix-broken install` might help, if the issue is indeed with APT.

If that doesn't resolve the issue, could you try to install the dex2jar using APT like this and let me know what you see:

```
sudo apt update
sudo apt install dex2jar
```

Thanks for testing this!

**Comment by citizenstaar** [comment] 2020-06-16 15:37
**remnux@remnux:~$ sudo apt update**
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                       
Hit:3 http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2 bionic InRelease                     
Hit:4 https://download.docker.com/linux/ubuntu bionic InRelease                                    
Hit:5 http://ppa.launchpad.net/gift/stable/ubuntu bionic InRelease                                 
Hit:6 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease                        
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                        
Hit:8 http://download.draios.com/stable/deb stable-amd64/ InRelease                                
Get:9 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                     
Hit:10 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu bionic InRelease                              
Get:11 http://us.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [694 kB]              
Get:12 http://ppa.launchpad.net/remnux/stable/ubuntu bionic InRelease [15.9 kB]                    
Get:13 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [486 kB]               
Hit:14 http://ppa.launchpad.net/sift/stable/ubuntu bionic InRelease                                
Get:15 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [969 kB]             
Hit:16 http://ppa.launchpad.net/wireshark-dev/stable/ubuntu bionic InRelease                       
Hit:17 http://www.inetsim.org/debian binary/ InRelease                                             
Get:18 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1,018 kB]   
Get:19 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [748 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,081 kB] 
Fetched 5,263 kB in 3s (1,625 kB/s)                                                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
**remnux@remnux:~$ sudo apt autoremove**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 de4dot : Depends: libdnlib2.1-cil (>= 2.1) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
**remnux@remnux:~$ sudo apt --fix-broken install**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  de4dot
0 upgraded, 0 newly installed, 1 to remove and 8 not upgraded.
1 not fully installed or removed.
After this operation, 1,478 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 182841 files and directories currently installed.)
Removing de4dot (3.1.41592.3405-1) ...
**remnux@remnux:~$ sudo apt install dex2jar**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dex2jar
0 upgraded, 1 newly installed, 0 to remove and 8 not upgraded.
Need to get 4,984 kB of archives.
After this operation, 6,083 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/remnux/stable/ubuntu bionic/main amd64 dex2jar all 2.1 [4,984 kB]
Fetched 4,984 kB in 8s (590 kB/s)                                                                  
Selecting previously unselected package dex2jar.
(Reading database ... 182829 files and directories currently installed.)
Preparing to unpack .../archives/dex2jar_2.1_all.deb ...
Unpacking dex2jar (2.1) ...
Setting up dex2jar (2.1) ...

**Comment by citizenstaar** [comment] 2020-06-16 15:38
Using the sample:
cd125b6db526113bacbf77447a12a32449fd289a1478be49725301fc81baaf7c

With the instructions here:

https://github.com/pxb1988/dex2jar/blob/2.x/README.md

I verified the result using jd-gui.

**Comment by lennyzeltser** [comment] 2020-06-17 00:45
OK, sounds like everything is working now. I'll close the issue, but if I misunderstood this, please let me know. Thanks for your help!

**Closed by lennyzeltser** 2020-06-17 00:45 UTC
